# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8088

# Spring配置
spring:
  datasource:
#    primary: db1
#    db1:
#      username: root
#      password: njrclsnddkjdem
#      url: jdbc:mysql://192.168.0.118/erp1_4.2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    db2:
      username: root
      password: njrclsnddkjdem
      url: jdbc:mysql://192.168.0.118/erp1_4.2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sn.entity

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 日志配置
logging:
  level:
    com:
      example:
        mapper: debug

