# 项目相关配置
erp:
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/File/uploadPath

spring:
  profiles:
    active: dev
  jmx:
   enabled: false
  aop:
    auto: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 使用的数据库索引，默认是0
    database: 0

shiro:

